### ISSUE TITLE
VelloVectorBundle Transform origin ?

### ISSUE THREAD

**Issue by tintincastro** [vectorgameexperts/bevy-vello#10]
Sorry if this question is stupid (bevy beginner here), but is it possible to set the transform origin of a VelloVectorBundle to the center of the vector instead of the bottom center?

I've seen the `compute_local_transform`  in the parser, but it doesn't seem accessible in bevy world.

Thanks in advance for your input.

**Comment by seabassjh** [comment]
This is currently not possible, but that is a use case I'd like bevy-vello to support. I'll make a patch release soon to add this feature.
Thanks for your input :)

**Comment by seabassjh** [comment]
Closing this issue because of the new feature introduced here: https://github.com/vectorgameexperts/bevy-vello/commit/aec0422ec83cd06a1c7f96d26795ed321ba66c96
